version: '2.2'

services:
  database:
    image: sgtux/database-devsecops
    networks:
      lan:
        ipv4_address: 172.22.22.10

networks:
  lan:
    ipam:
      config:
        - subnet: 172.22.22.0/24